const ActionTypes={
  REST_LOADING:" REST_LOADING",
  REST_SUCCESS:"REST_SUCCESS",
  REST_ERROR:"REST_ERROR",  
  CART_LOADING:" CART_LOADING",
  CART_SUCCESS:"CART_SUCCESS",
  CART_ERROR:"CART_ERROR", 
  CREATE_ITEM:"CREATE_ITEM",
  DELETE_ITEM:"DELETE_ITEM",
  UPDATE_ITEM:"UPDATE_ITEM",
  OPEN_LOGIN: "OPEN_LOGIN",
  CLOSE_LOGIN: "CLOSE_LOGIN",

};
export default ActionTypes;
